employees/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'employees'

router = routers.DefaultRouter()
router.register('salaries', views.SalaryView)
router.register('groups', views.GroupView)

urlpatterns = [
	path('', include(router.urls), name="salary-api"),
	path('manage', views.manage, name="manage"),
	path('salaries/getid/<int:id_salary_finger>', views.get_salary_id, name="manage"),
	path('groups/getid/<int:id>', views.get_group_id, name="manage_group"),
]

pointage/urls.py
from django.urls import path, include
from .views import profile, reports,manage
from . import views
from rest_framework import routers
from employees.views import GroupView
app_name = 'pointage'
router = routers.DefaultRouter()
router.register('times', views.TimeEnterView)
router.register('groups', GroupView)
router.register('Breacks', views.BreakView)
router.register('salaries', views.SalaryView)
router.register('holidays', views.HolidaysView)
urlpatterns = [
    path('profile/<int:id>', profile, name="profile"),
    path('', include(router.urls), name="TimeEnter-api"),
    path('reports', reports, name="reports"),
    path('gerer_tempe/', manage, name="gererTempe"),
    path('times/getid/<int:id>', views.get_time_id, name="get_id_time"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page),
    path('employees/', include('employees.urls', namespace='employees')),
    path('pointage/', include('pointage.urls', namespace='pointage')),
    path('logout/', logout_view, name="logout")
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/global/home.html
{% extends 'base.html' %}

{% block title %} Home page {% endblock title %}

{% block content %}
<div class="container-fluid">
	<!-- Page-Title -->
	<div class="row">
		<div class="col-sm-12">
			<div class="page-title-box">
				<h4 class="page-title">Tableau de bord</h4>
			</div>
		</div>
	</div>
	<!-- end page title end breadcrumb -->
	<div class="row">
		<div class="col-md-6 col-xl-3">
			<div class="mini-stat clearfix bg-white">
				<a href="{% url 'employees:manage' %}"><span class="mini-stat-icon bg-light"><i class="fa fa-user"></i></span></a>
				<div class="mini-stat-info text-right text-muted">
					<span class="counter text-danger">{{nb_salary}}</span>
					Salariés
				</div>
			</div>
		</div>

		<div class="col-md-6 col-xl-3">
			<div class="mini-stat clearfix bg-success">
				<a href="{% url 'pointage:reports' %}"><span class="mini-stat-icon bg-light"><i class="fa fa-cloud"></i></span></a>
				<div class="mini-stat-info text-right text-white">
					Rapport
				</div>
				<p class="mb-0 m-t-20 text-light"> <span class="pull-right"><a href="">Plus de details</a></span></p>
			</div>
		</div>

		<div class="col-md-6 col-xl-3">
			<div class="mini-stat clearfix bg-white">
				<a href="{% url 'pointage:gererTempe' %}"><span class="mini-stat-icon bg-light"><i class="mdi mdi-cube-outline text-warning"></i></span></a>
				<div class="mini-stat-info text-right text-muted">
					<a href="{% url 'pointage:gererTempe' %}">Gere les périodes</a>
				</div>
			</div>
		</div>

		<div class="col-md-6 col-xl-3">
			<div class="mini-stat clearfix bg-info">
				<a href="{% url 'employees:manage' %}"><span class="mini-stat-icon bg-light"><i class="fa fa-users"></i></span></a>
				<div class="mini-stat-info text-right text-light">
					<span class="counter text-white">{{nb_group}}</span>
					Total groups
				</div>
			</div>
		</div>

	</div>


</div> <!-- end container -->
{% endblock %}